/**
 * Supported cinematic combat and choreography event types.
 */
export type CinematicEventType =
  | 'hit'
  | 'parry'
  | 'dodge'
  | 'death'
  | 'weapon_formation'
  | 'weapon_destruction'
  | 'transformation'
  | 'explosion'
  | 'aura_activation';

/**
 * 3D spatial coordinate tuple [x, y, z].
 */
export type Vector3Tuple = [number, number, number];

/**
 * Base cinematic event contract generated by the combat/director engine.
 */
export interface CinematicEventBase {
  id: string;
  type: CinematicEventType;
  timestamp: number;
  duration?: number;
  intensity: number; // 0.0 - 1.0
  position: Vector3Tuple;
}

export interface HitCinematicEvent extends CinematicEventBase {
  type: 'hit';
  attackerId: string;
  targetId: string;
  impactForce: number;
  critical: boolean;
}

export interface ParryCinematicEvent extends CinematicEventBase {
  type: 'parry';
  defenderId: string;
  attackerId: string;
  sparkIntensity: number;
}

export interface DodgeCinematicEvent extends CinematicEventBase {
  type: 'dodge';
  fighterId: string;
  evasionDirection: Vector3Tuple;
}

export interface DeathCinematicEvent extends CinematicEventBase {
  type: 'death';
  fighterId: string;
  cause: string;
}

export interface WeaponFormationCinematicEvent extends CinematicEventBase {
  type: 'weapon_formation';
  fighterId: string;
  weaponType: 'blade' | 'spear' | 'staff' | 'scythe' | 'energy_claws';
}

export interface WeaponDestructionCinematicEvent extends CinematicEventBase {
  type: 'weapon_destruction';
  fighterId: string;
  fragmentCount: number;
}

export interface TransformationCinematicEvent extends CinematicEventBase {
  type: 'transformation';
  fighterId: string;
  stageName: string;
}

export interface ExplosionCinematicEvent extends CinematicEventBase {
  type: 'explosion';
  radius: number;
  shockwaveVelocity: number;
}

export interface AuraActivationCinematicEvent extends CinematicEventBase {
  type: 'aura_activation';
  fighterId: string;
  auraColor: string;
  element: 'fire' | 'lightning' | 'void' | 'kinetic';
}

/**
 * Union of all cinematic events.
 */
export type CinematicEvent =
  | HitCinematicEvent
  | ParryCinematicEvent
  | DodgeCinematicEvent
  | DeathCinematicEvent
  | WeaponFormationCinematicEvent
  | WeaponDestructionCinematicEvent
  | TransformationCinematicEvent
  | ExplosionCinematicEvent
  | AuraActivationCinematicEvent;

/**
 * Camera cut and framing director directives.
 */
export type CameraShotType =
  | 'wide_master'
  | 'medium_duel'
  | 'close_up'
  | 'low_angle_hero'
  | 'high_angle_god'
  | 'dutch_tilt_clash'
  | 'orbit_strike'
  | 'first_person_pov';

export interface CameraCutDirective {
  timestamp: number;
  shotType: CameraShotType;
  targetPosition: Vector3Tuple;
  focalLength: number;
  dofAperture?: number;
  shakeIntensity?: number;
  duration?: number;
}

/**
 * Slow motion trigger specifications driven by cinematic director.
 */
export interface SlowMotionDirective {
  startTime: number;
  duration: number;
  timeScale: number; // e.g. 0.1 for 10x slow-mo
  easing: 'easeIn' | 'easeOut' | 'easeInOut' | 'bullet_time';
}

// ---------------------------------------------------------------------------
// Runtime combat events (what the choreographer actually emits every frame)
// ---------------------------------------------------------------------------

export type PhraseKind =
  | 'intro'
  | 'tension'
  | 'summon'
  | 'pet_assault'
  | 'standoff'
  | 'exchange'
  | 'dash_clash'
  | 'weapon_duel'
  | 'clone_jutsu'
  | 'ki_barrage'
  | 'beam_clash'
  | 'air_combo'
  | 'power_up'
  | 'mirror_clash'
  | 'blade_lock'
  | 'grapple'
  | 'super'
  | 'ultra'
  | 'finisher'
  /** Weapon thrown or planted, fists in the middle, weapon called back (or formed mid-combo) */
  | 'hybrid'
  /** Speedster vocabulary: flash steps, multi-strikes, phantom assaults, velocity breaks */
  | 'speed_blitz'
  /** A flurry: a blur of blows on sixteenth notes, a guard that breaks, a launcher on the downbeat */
  | 'rush';

export type CombatEventType =
  | 'phrase'
  | 'caption'
  | 'hit'
  | 'block'
  | 'dodge'
  | 'clash'
  | 'dash'
  | 'weapon_form'
  | 'weapon_shatter'
  | 'clone_spawn'
  | 'clone_pop'
  | 'projectile_fire'
  | 'projectile_hit'
  | 'projectile_deflect'
  | 'charge'
  | 'beam_start'
  | 'beam_pulse'
  | 'beam_end'
  | 'launch'
  | 'slam'
  | 'powerup'
  | 'death'
  | 'reform'
  | 'appear'
  | 'fade_out'
  | 'pet_spawn'
  | 'pet_lunge'
  | 'pet_hit'
  | 'pet_pop'
  | 'breath_start'
  | 'summon_start'
  | 'summon_morph'
  | 'summon_launch'
  | 'summon_impact'
  | 'summon_split'
  | 'tech_release'
  | 'tech_hit'
  | 'teleport'
  | 'transform'
  | 'lock'
  /** A strike has started its wind-up: `beats` until impact, `intensity` its weight */
  | 'windup'
  // ---- supermoves (local / medium area): started → charge → released → impact
  | 'super_started'
  | 'super_charge'
  | 'super_released'
  | 'super_impact'
  // ---- ultramoves (arena scale): started → formation → peak → impact → aftermath
  | 'ultra_started'
  | 'ultra_formation'
  | 'ultra_peak'
  | 'ultra_impact'
  | 'ultra_aftermath'
  // ---- weapon ↔ hand-to-hand transitions
  | 'weapon_release'
  | 'weapon_recall'
  | 'weapon_manifest'
  // ---- speed
  | 'speed_dash'
  | 'velocity_break'
  | 'perfect_dodge';

export interface CombatEvent {
  type: CombatEventType;
  pos: Vector3Tuple;
  dir: Vector3Tuple;
  /** 0 … 1 */
  intensity: number;
  /** Acting fighter (0 / 1) */
  fighter: number;
  /** Receiving fighter (0 / 1) */
  target: number;
  critical?: boolean;
  cloneIndex?: number;
  phrase?: PhraseKind;
  /** Phrase length in beats */
  beats?: number;
  label?: string;
  sub?: string;
  /** Area the moment covers (metres): lets the camera pull back far enough to show its scale */
  radius?: number;
}
