import { it } from 'vitest';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { analyzeSamples } from '../src/audio/analysis/analyze';
import { analyzeSong as analyzeV1 } from './v1/SongAnalyzerV1';
import { beatFMeasure, renderSong, SynthOptions, SynthSection } from '../tests/helpers/synth';

/**
 * V1 vs V2 offline analysis on synthetic songs with known ground truth.
 * Writes bench/results/audio-analysis.md.
 *
 * Real songs: set CINEVIZ_BENCH_AUDIO to a comma-separated list of raw mono float32 files
 * with their rate, e.g. "a.f32@48000,b.f32@44100" (decode with any tool, e.g.
 * `ffmpeg -i song.mp3 -ac 1 -f f32le a.f32`).
 */
const full = (bars: number, extra: Partial<SynthSection> = {}): SynthSection => ({ bars, kick: true, snare: true, hat: true, bass: true, chords: [0, 7, 9, 5], level: 0.8, ...extra });
const verse = (bars: number): SynthSection => ({ bars, kick: true, hat: true, chords: [2, 9], level: 0.45 });

const CASES: { name: string; o: SynthOptions; drops?: number[] }[] = [
  { name: 'steady 124 BPM', o: { bpm: 124, sections: [verse(8), full(8), verse(8), full(8)] } },
  { name: 'tempo change 110→140', o: { sections: [full(12, { bpm: 110, chords: [0, 7] }), full(12, { bpm: 140, chords: [0, 7] })] } },
  { name: 'white-noise tail (5 s)', o: { bpm: 124, sections: [verse(8), full(16)], tail: { kind: 'white', seconds: 5, level: 0.08 } } },
  { name: 'silence tail (4 s)', o: { bpm: 124, sections: [verse(8), full(16)], tail: { kind: 'silence', seconds: 4 } } },
  { name: 'hiss tail (6 s)', o: { bpm: 124, sections: [verse(8), full(16)], tail: { kind: 'hiss', seconds: 6, level: 0.03 } } },
  { name: 'quiet bridge', o: { bpm: 124, sections: [full(8), { bars: 8, chords: [4, 11], level: 0.12 }, full(8)] } },
  { name: 'final sustained note', o: { bpm: 124, sections: [verse(8), full(12)], sustain: { seconds: 4, root: 0, decay: 0.8 }, tail: { kind: 'silence', seconds: 2 } } },
  { name: 'abrupt end', o: { bpm: 124, sections: [verse(8), full(12)], abrupt: true } },
  {
    name: 'EDM: intro/build/drop/breakdown/drop/outro',
    o: {
      bpm: 128,
      sections: [
        { bars: 8, hat: true, chords: [9, 5], level: 0.35 },
        { bars: 8, snare: true, hat: 'sixteenths', chords: [9, 5], build: true, level: 0.7 },
        full(16, { chords: [9, 5, 0, 7], bright: true, level: 0.95 }),
        { bars: 8, chords: [9, 5], level: 0.25 },
        full(16, { chords: [9, 5, 0, 7], bright: true, level: 0.95 }),
        { bars: 8, chords: [9], level: 0.3 },
      ],
    },
    drops: [2, 4],
  },
];

const f = (v: number, d = 2) => v.toFixed(d);

it('audio analysis: V1 vs V2', () => {
  const rows: string[] = [];
  rows.push('| Case | True BPM | V1 BPM | V2 BPM | V1 beat F | V2 beat F | V2 beat offset (ms) | True music end (s) | V1 plans to (s) | V2 musical end (s) | V2 ending | V1 drops (s) | V2 drops (s) | V1 ms | V2 ms |');
  rows.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|');
  for (const c of CASES) {
    const s = renderSong(c.o);
    const t1 = performance.now();
    const v1 = analyzeV1({ sampleRate: s.sr, length: s.samples.length, numberOfChannels: 1, duration: s.duration, getChannelData: () => s.samples } as unknown as AudioBuffer);
    const v1ms = performance.now() - t1;
    const v2 = analyzeSamples(s.samples, s.sr);
    const ref = s.beats;
    const inMusic = (b: ArrayLike<number>, end: number) => Array.from(b).filter((t) => t < end);
    const trueBpm = c.o.bpm ? String(c.o.bpm) : c.o.sections.map((x) => x.bpm).join('→');
    const err = ref.map((r) => {
      let m = 9;
      for (const d of v2.beats) if (Math.abs(d - r) < Math.abs(m)) m = d - r;
      return m;
    }).filter((m) => Math.abs(m) < 0.1);
    const off = (err.reduce((a, b) => a + Math.abs(b), 0) / Math.max(1, err.length)) * 1000;
    // V1 has no musical end: it plans the finale 16 beats before the end of its beat grid (the file end)
    const v1End = v1.beats[v1.beats.length - 1]!;
    rows.push(`| ${c.name} | ${trueBpm} | ${f(v1.bpm, 1)} | ${f(v2.bpm, 1)} | ${f(beatFMeasure(inMusic(v1.beats, s.musicEnd), ref))} | ${f(beatFMeasure(inMusic(v2.beats, v2.musicalEnd), ref))} | ${f(off, 1)} | ${f(s.musicEnd)} | ${f(v1End)} | ${f(v2.musicalEnd)} | ${v2.ending.kind}/${v2.ending.tail} (${f(v2.ending.confidence)}) | ${v1.drops.map((d) => f(v1.beats[d]!, 1)).join(', ') || '—'} | ${v2.dropEvents.map((d) => f(d.time, 1)).join(', ') || '—'} | ${f(v1ms, 0)} | ${f(v2.analysisMs, 0)} |`);
  }
  const lines = [
    '# Audio analysis: V1 vs V2',
    '',
    'Generated by `npm run bench` (bench/analysis.report.ts). Synthetic songs rendered at 22.05 kHz with known beats, sections and musical end (tests/helpers/synth.ts).',
    '',
    ...rows,
    '',
  ];
  if (process.env.CINEVIZ_BENCH_AUDIO) {
    lines.push('## Real songs', '', '| File | Duration (s) | V1 BPM | V2 BPM | V2 tempo conf | Musical start–end (s) | Ending | V1 drops (s) | V2 drops (s) | Sections | V1 ms | V2 ms |', '|---|---|---|---|---|---|---|---|---|---|---|---|');
    for (const spec of process.env.CINEVIZ_BENCH_AUDIO.split(',')) {
      const [path, rate] = spec.split('@');
      if (!path || !existsSync(path)) continue;
      const buf = readFileSync(path);
      const x = new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4);
      const sr = Number(rate ?? 44100);
      const t1 = performance.now();
      const v1 = analyzeV1({ sampleRate: sr, length: x.length, numberOfChannels: 1, duration: x.length / sr, getChannelData: () => x } as unknown as AudioBuffer);
      const v1ms = performance.now() - t1;
      const v2 = analyzeSamples(x, sr);
      lines.push(`| ${path.split(/[\\/]/).pop()} | ${f(v2.fileDuration)} | ${f(v1.bpm)} | ${f(v2.bpm)} | ${f(v2.tempo.confidence)} | ${f(v2.musicalStart)}–${f(v2.musicalEnd)} | ${v2.ending.kind}/${v2.ending.tail} (${f(v2.ending.confidence)}) | ${v1.drops.map((d) => f(v1.beats[d]!, 1)).join(', ')} | ${v2.dropEvents.map((d) => f(d.time, 1)).join(', ')} | ${v2.sections.map((s) => `${f(s.start, 0)} ${s.type}`).join(', ')} | ${f(v1ms, 0)} | ${f(v2.analysisMs, 0)} |`);
    }
  }
  mkdirSync('bench/results', { recursive: true });
  writeFileSync('bench/results/audio-analysis.md', lines.join('\n') + '\n');
});
