import { it } from 'vitest';
import { mkdirSync, writeFileSync } from 'fs';
import type { PlanSection, SongPlan } from '../src/engine/simulation/combat/CombatEngine';
import { planFromSections, runShow } from '../tests/helpers/headless';

/**
 * Choreography with vs without the song structure (the V1 engine only knew intro end,
 * outro start, drops and loudness). Writes bench/results/choreography.md.
 */
const SONG: PlanSection[] = [
  { start: 0, end: 32, type: 'intro', energy: 0.3 },
  { start: 32, end: 96, type: 'verse', energy: 0.55 },
  { start: 96, end: 128, type: 'build', energy: 0.6 },
  { start: 128, end: 192, type: 'drop', energy: 0.95 },
  { start: 192, end: 256, type: 'breakdown', energy: 0.25 },
  { start: 256, end: 288, type: 'build', energy: 0.6 },
  { start: 288, end: 352, type: 'drop', energy: 0.95 },
  { start: 352, end: 384, type: 'outro', energy: 0.4 },
];
const SEEDS = [1, 2, 3, 4, 5, 6, 7, 8];
const CALM = new Set(['standoff', 'tension', 'blade_lock', 'grapple']);
const IMPACT = new Set(['tech_hit', 'super_impact', 'ultra_impact', 'summon_impact', 'beam_start', 'clash', 'slam', 'launch']);

function run(structure: boolean) {
  const plan: SongPlan = planFromSections(SONG, { drops: [128, 288], finalPeak: 320 });
  if (!structure) {
    delete plan.sections;
    delete plan.builds;
    plan.finalPeak = null;
    delete plan.downbeatOffset;
  }
  const bySec: Record<string, Record<string, number>> = {};
  let landed = 0, drops = 0, ultraOffStructure = 0, ultras = 0;
  for (const seed of SEEDS) {
    const l = runShow({ seed, plan, seconds: (384 / 120) * 60 + 4, fps: 60 });
    for (const p of l.phrases) {
      const s = SONG.find((x) => p.beat >= x.start && p.beat < x.end)?.type ?? '?';
      (bySec[s] ??= {})[p.kind] = (bySec[s]![p.kind] ?? 0) + 1;
    }
    for (const d of plan.drops) {
      drops++;
      if (l.events.some((e, i) => IMPACT.has(e.type) && Math.abs(l.beats[i]! - d) < 1.5)) landed++;
    }
    l.events.forEach((e, i) => {
      if (e.type !== 'ultra_impact') return;
      ultras++;
      const b = l.beats[i]!;
      const sec = SONG.find((x) => b >= x.start && b < x.end)?.type;
      if (!plan.drops.some((d) => Math.abs(b - d) < 1) && !['drop', 'chorus', 'outro'].includes(sec ?? '')) ultraOffStructure++;
    });
  }
  return { bySec, landed, drops, ultras, ultraOffStructure };
}

it('choreography: with vs without song structure', () => {
  const v1 = run(false), v2 = run(true);
  const lines = ['# Choreography and song structure', '', 'Generated by `npm run bench` (bench/choreography.report.ts). One song plan (intro, verse, build, drop, breakdown, build, drop, outro; drops on beats 128 and 288), 8 seeds, 120 BPM.', ''];
  lines.push('| Section | Without structure: calm share | With structure: calm share | Without: tension + power-up | With: tension + power-up | Without: super + rush | With: super + rush |', '|---|---|---|---|---|---|---|');
  for (const s of ['verse', 'build', 'drop', 'breakdown', 'outro']) {
    const a = v1.bySec[s] ?? {}, b = v2.bySec[s] ?? {};
    const tot = (m: Record<string, number>) => Object.values(m).reduce((x, y) => x + y, 0) || 1;
    const share = (m: Record<string, number>, keys: string[]) => keys.reduce((x, k) => x + (m[k] ?? 0), 0) / tot(m);
    const pc = (v: number) => `${(v * 100).toFixed(0)} %`;
    lines.push(`| ${s} | ${pc(share(a, [...CALM]))} | ${pc(share(b, [...CALM]))} | ${pc(share(a, ['tension', 'power_up']))} | ${pc(share(b, ['tension', 'power_up']))} | ${pc(share(a, ['super', 'rush']))} | ${pc(share(b, ['super', 'rush']))} |`);
  }
  lines.push('', '| | Without structure | With structure |', '|---|---|---|');
  lines.push(`| Drops with a set-piece impact on the beat (±1.5) | ${v1.landed} / ${v1.drops} | ${v2.landed} / ${v2.drops} |`);
  lines.push(`| Ultramove impacts | ${v1.ultras} | ${v2.ultras} |`);
  lines.push(`| … outside drops / loud sections / the finale | ${v1.ultraOffStructure} | ${v2.ultraOffStructure} |`);
  lines.push('', 'Both columns include the V2 fix to `planDrop` (a drop too close for an ultramove falls back to a super, clash, beam or summon instead of being dropped), so the drop row measures the structure, not the fix.');
  mkdirSync('bench/results', { recursive: true });
  writeFileSync('bench/results/choreography.md', lines.join('\n') + '\n');
});
