import { it } from 'vitest';
import { mkdirSync, writeFileSync } from 'fs';
import { analyzeSamples } from '../src/audio/analysis/analyze';
import { extractFeatures, toAnalysisRate } from '../src/audio/analysis/features';
import { trackBeats } from '../src/audio/analysis/beats';
import { findMusicalBounds } from '../src/audio/analysis/ending';
import { BodyConstraints } from '../src/engine/simulation/combat/Constraints';
import { CombatEngine } from '../src/engine/simulation/combat/CombatEngine';
import { analyzeSong as analyzeV1 } from './v1/SongAnalyzerV1';
import { DEFAULT_PARAMS, musicState, planFromSections } from '../tests/helpers/headless';
import { renderSong, SynthSection } from '../tests/helpers/synth';

/** Timings (median of several runs). Writes bench/results/timing.md. */
const median = (a: number[]) => a.slice().sort((x, y) => x - y)[Math.floor(a.length / 2)]!;
function time(fn: () => void, runs: number): number {
  fn();
  const t: number[] = [];
  for (let i = 0; i < runs; i++) {
    const t0 = performance.now();
    fn();
    t.push(performance.now() - t0);
  }
  return median(t);
}

it('timing', () => {
  const full = (bars: number): SynthSection => ({ bars, kick: true, snare: true, hat: true, bass: true, chords: [0, 7, 9, 5], level: 0.8 });
  const verse = (bars: number): SynthSection => ({ bars, kick: true, hat: true, chords: [2, 9], level: 0.45 });
  const song = renderSong({ sr: 44100, bpm: 124, sections: [verse(16), full(16), verse(16), full(16), verse(16), full(16), full(16)] });
  const buffer = { sampleRate: song.sr, length: song.samples.length, numberOfChannels: 1, duration: song.duration, getChannelData: () => song.samples } as unknown as AudioBuffer;
  const lines = ['# Timing', '', `Generated by \`npm run bench\` (bench/timing.report.ts), Node ${process.version}, median of 5 runs after a warm-up.`, ''];
  lines.push(`## Offline analysis of a ${song.duration.toFixed(0)} s song at 44.1 kHz`, '', '| Stage | ms |', '|---|---|');
  lines.push(`| V1 analyzeSong (whole) | ${time(() => analyzeV1(buffer), 5).toFixed(0)} |`);
  lines.push(`| **V2 analyzeSamples (whole)** | **${time(() => analyzeSamples(song.samples, song.sr), 5).toFixed(0)}** |`);
  const { x, sr } = toAnalysisRate(song.samples, song.sr);
  const F = extractFeatures(x, sr);
  const g = trackBeats(F, 0, F.frames);
  lines.push(`| V2: decimate 44.1 → 22.05 kHz | ${time(() => toAnalysisRate(song.samples, song.sr), 5).toFixed(0)} |`);
  lines.push(`| V2: frame features (FFT, bands, flux, flatness, chroma) | ${time(() => extractFeatures(x, sr), 5).toFixed(0)} |`);
  lines.push(`| V2: tempo + beats (one pass) | ${time(() => trackBeats(F, 0, F.frames), 5).toFixed(0)} |`);
  lines.push(`| V2: musical start / end | ${time(() => findMusicalBounds(F, g.period, song.duration), 5).toFixed(0)} |`);

  // Two engines on the same seed, measured in interleaved rounds (fair JIT / cache state)
  const make = () => {
    const e = new CombatEngine();
    e.init(7);
    e.setPlan(planFromSections([{ start: 0, end: 32, type: 'intro', energy: 0.3 }, { start: 32, end: 4000, type: 'chorus', energy: 0.85 }]));
    const m = musicState(124);
    e.start(0);
    return () => {
      m.time += 1 / 60;
      e.update(1 / 60, m, DEFAULT_PARAMS);
    };
  };
  const steps = [make(), make()];
  const run = (k: number, n: number) => {
    BodyConstraints.enabled = k === 1;
    const t0 = performance.now();
    for (let i = 0; i < n; i++) steps[k]!();
    BodyConstraints.enabled = true;
    return (performance.now() - t0) / n;
  };
  run(0, 1200);
  run(1, 1200);
  const res: number[][] = [[], []];
  for (let r = 0; r < 10; r++) for (const k of [0, 1]) res[k]!.push(run(k, 300));
  lines.push('', '## Combat engine update (one 60 fps step, mid-fight, all actors)', '', 'Interleaved rounds of 300 steps, median.', '', '| Layer | ms / update |', '|---|---|');
  lines.push(`| without contact / grip layer | ${median(res[0]!).toFixed(3)} |`);
  lines.push(`| with contact / grip layer | ${median(res[1]!).toFixed(3)} |`);
  lines.push('', 'The frame budget at 60 fps is 16.7 ms; particles and rendering are unchanged by V2.');
  mkdirSync('bench/results', { recursive: true });
  writeFileSync('bench/results/timing.md', lines.join('\n') + '\n');
});
